apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:yiDIeJhjtC1oQUrB8eZyKWzPXeLocGTSod/6ikv/OMbVGFGh6eYplqpbTytMixaWcpYxC/gTrA4co/Wkep+l04gHXeYQ2KIsgaxIE8SU/jfR4gJnYZ+mtJTPX7iHyR/0lK/KJjrbm20sq3c95J79ufhi2STMthcbjT/CDMzEOWhxN2bAb2xbtht2eUsWewj2TKPypq77Htb6PE0eYjgsr0smgHX3k3o2/NbfTd2cgte19h/vyyB03P5i2G/ED+hiZKbXhJQhW3i45UbhaaTQeng93E8kmS+zbxWArxlksKL4T03XovK5obHxamg=,iv:ecRUi+/zMIfNL92g7ERTlYaCLaH+mzkE4PjzBPtR0WU=,tag:fYxNHbg0ft7vDddS41/3JA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eq34vq9sccxsrx08a4d27kmw393a7p8ga8wdm4glsnn9nhgsvafqkf75tm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OFUvbzJObjNCbE5HT3Vs
            V0ZNTjkvK2hXZGVJZE4vZkJpdHRJZno3SERzClZ6T0VEaXNQQmFlSG1iV2h4L0l6
            cmVkVW5TQzhWU3dyZE5rT3hBYTVFZFkKLS0tIE9yUXJrVVFIWENlOTdJS3p5aTlS
            WW44eUduMkdYNjgxSzF5ZXBYbXY0TEEKOmbVAh45HpEWL+wSLt2afXYl3MRugFvp
            lvw/O8LjbOrv1FA1SfossDy0LUyBMkaEcAX5usfA0FFmD4nt5qEV4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T13:15:36Z"
    mac: ENC[AES256_GCM,data:zgtfjvx1s0Pl0aTI58FNLONPIHPYZn4MsglbB5CSdk03NXZZVDgeYImt+TAzRHgSf0vpNP4DB4n9PgHYGmcdCz3aVn+kCrX/9uJgr64hSI7QDm9hxyaRr9pFd+OCvT94CxfccWfqYI5z9d0yYxyRNyUu+qVmjY2hBEZLQo6EyXg=,iv:OXgnsifEREdONKIILKWE2RxsgoqtCgGEgEXx8Zzti5Y=,tag:dfqGxwLJezU1dpeToLEgIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
