---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
spec:
  encryptedData:
    secret_key: AgAZWa0J9bceo7NJrLZB1pT5gqOjZjOS9BGMDjgsFNs3L/EJH4qi2ijvalUk2k9R3WaLJ/cytofCYvmKEB2RyxftG6Af1SmOLb03rkD5R1ZvQk77qde6vepkcas5EH8dmQzqjXc+9PepkDDVXYuz5uFFBPrG9hWYEtACrYjhvbb5pAZyOUL2GBlb2MDkjaf4N+zhndf1hW0jMlF86PC0/2o6C+LlOwAxRGGJEj2c7/V0h1ny+PYpBySO09MzuO6ZZ+5gAPYrd6arALYfe6j1MFGvsA0VE33Y9TweF5JAE87Ui61CPK1t7LbyGFC8nN0ASjfd85Z1OXP5FtZofm0yCbXg+onz28TYvz53EphqVq+0kw/sUw16fQByc9QkJRGCG4o+cuaUYFXBjnXKNyVpHcJPkcpcSOOVcR4Vd2FC1/V9m1Sb4mmYe242Mkuzf18aV1GCuxnrAdUdAzQeyTMAZi2smIlYJVZprr+k2ua4ciJf4gXMu+6z4HHFbYbRGMDDE02q1nHorLJaMpayTyqAK/T+RntplGZqsRPjNCowGwGHdWwoJpi7iMVpVwECYuBAG59ZG/NjdkYkr9vN/GYMYgtStB6P32pU6mSQY88hEMcTaTe1ZQp1TM6fgsJDgO5wtg9BYLDOj9gUUoIGxQLrqtAchUwsw0bQ6S7Yi2cGrSMQTEqyZZf7kxccHb8E9F8Y8YwQw+DrBpWrWWirce+sJOOYNTIKR3RPpvQiKiYr6tDDNJP6XngyFGwDCWYfs5e0fLbUOIhu4032xV730VzJgypb4dk3zJwaYwuF0SS4fbS6Kg==
  template:
    metadata:
      name: authentik-secrets
