---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    secret_key: AgABILpv6GESes9ohO6ZbJgpjc80JBQ1tRfRh50DJVVDwrsk8cvmHl8MCf+ZcV79n5EirUIVaH0LSztSoGsDEXw0gET/7ymw/ptsjk3KP1DMMy5dGfjMgXC9xdEwHQrkIqqeOKH0iJAROHQp/Kd4tovi3wBffF1uqw7BC6gkl2KsTeEbbr5WifhB3CnttPS4rO7IhKcCTqIRaDBYDEiSfi+x6wDyvdph1Dy5lZAloJNN3GhwhRGPV3EdxTktWf9iIX6okOvKxOBFdhPEp9G9oPk3sDF6jWHJrhs3sovZ7DOGv9mMF22rtFFyekl7IQpmtP/gs78MhH2R8hYE3Ymstv5ixujRA+riPg82vpQWMg0Q35YfaOAAUtaV6gGzyenpGgoI7QBlnBAzdaGAlgEd4pnqMpaWqGjqSJcO8M4wk0JSn7+Ed/+i3k1HsQq2fJy6J/QR9QYExH1E2Daz7QjEmblSEckH+zcRzJjjmeSN+7sQ5Z4BJ94KZJKvySTTKhcnWkhMN7TBxAKiOrkoHX60oYCjnaDztBCBiq2QewZq3puuTkdONzwhmTgDiby6CUwMkpy8qLSdLhEg4Nj6V/YB810l7E845FBtdQE7sWawc3YfK3IkIyt6DHReFPGg40Rx4aR795VbVUEGGDr/gqPkHl2bwQboPNJHc4fhkBFoiIwUiyXQ5gyyYdYQjwyWiLbZ1S44mgLuNysncQx0Bt080ve3Rfb0oT4+wlK4IN/ABOXOhQMb1ps+sLvOnld5EFQNg4vxVcfSTYYOx+EB7vIlEa4IQDIEEqCcBOgI+YH2+JY+gA==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
