---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: authentik
spec:
  encryptedData:
    credentials.json: AgBZEux/ceysaoXw0q1CYhBe3oqapZtCQy6BnjhMUmPLwMcr/BormibatNRBIAhaofPko4A9XUDSXs6UjffI2r3yRxud3W8pqkgoR9TlvddymPnhVblcAJ89Tv1JWsnrh4qT8qDkJ7gbnymhRV+SA4plnWVJGxjtRH07wiF8JmbHWf7SHYmBfOSptCirG/DUMrX7qcuhU9mkdiHu4ziMy9l1lphwyAc3khu5e01IS1wt4u86chHiIjm+C1KJJrziEsmJW0hSbQvpgUVs+ShMcWNiMOdg19Fuq8+QZUc/swMifu3DRZz5a5sPavEKIJHuKK6kX6aV4Al/hOTWLgwE0c2VEjnBjyULaTnEG5MvnmxjELT1ye6Fh3TmGZTIuWgSU8R+SXidxm5bAsiIaZ/BCGIyCis7EH0sSEak8RyUV7tP4611hb3T0S+QaA6OFnpXx8oGrSYFTZKY78upo7EqIu05XfXX+jE0A3iyen2CuUJXbAKKBnEtQm9wBpQJe37aza1bVhlcbrrJglua+HNPq31AxOqQ+nM7md3phfWZMZyDX/QocN6ofdzZ6a47o4R+Jzmvyx3LkcG7v/mUuEeUe0pJ8Qgc/16QiiYez+Kjgz+fWcjGe4zYLnaxT0mKt8PzuXd+XC7eEzHiA406qjAX1AyYDvH3DxpCVjiyUUIucTjxXJ3qr5KBblydNF7atWNmEfDOdpB9aqSbXTAY/S1t3MHyenkfQtLO9LABo2UIDVz1tFPEHpbzxn2EHY7SiEc/gbVZsCZHpTo+tJDfPnBfIocaRAAN8lRxS3HXGd9UxYzt1UjWd7cJHC9zZESbeGyljAIny1iN26wvfGYMFkI9g77XNXyfQamrLpSeVKvk1r8UX2rmrjhO6f4DXzGp5Bg93bPmUo+1qu4GrmcGsvipk7K+QKWAGTzDi+tHEqqnBUGd
  template:
    metadata:
      name: tunnel-credentials
      namespace: authentik
