---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: authentik
spec:
  encryptedData:
    credentials.json: AgARF8swqN+yc+wCY5PrpZ/0HCxNGo44njlU7IIFUPMOxlVLs9WwN+6F/QL4uVXoXGRryojha7jFbE2oZRj+Wt/1CWjHDp3qALe21CGYB7jZl8CgwTrOgMLliQrD84hPkf+m81cfvnI+3kduIlZTTczz0yh65YUjhRwT+/oC6yR3oORgClMsXSlcjy05anZgKZ/Cwvy5C+kZ50qUste7gQ1DDLegKecGcByin+H1gti9jwaJIAJ0sj+JDMxif9r3Hj0KYgNO/XIGKVK+EdkemMYcHxLkmiK2oL7jlldCpGt5a9I7fEDI22qbPHeWkEiV+JFiKWSELTfT/CqxuHRowqABcrJ0+SDn4R2frXPdiMA6M4PxLfwIHxWQE1ERe5tsCVhyXza3B8sU0O7FlS8kkeCz4K/D6d3XQa0NUoEUdguEtv2NHrTKhTPRhQYQqjrE7JXjJQURhzKVk4OLy0avjua2DZGOyKGYyTTNB4tWi+Mtf3XjNLr+S3PCjfdJsjHff0gZJVWc6UIJ63MDdeYRGgN+NQztvtj/zr9c0pph0CLvgXOBkHB78IOtq//1swZWlRmHRhoNFBj1Ewn4NzJnarnYltzjX1Dm7FUELD/iRpyIcl4YQ8yLUry0NYfc4fEF+zgy1UA0bMQOhTUzUA2+KAOnI/1YxhbEkcBJzpx6eaYoAIS43EUdogYBhFqjpN9yLsi6O8bWdHNwy5brt9NvI6GA3JohJ5wV215e07EVw6Q/IjfgfNukDC7xagEmT+6w4udaWrTO3G+Omwd41daJmdjh0HHljzmjfgw8oXWxfl77x2vLHLRxpq2DEhkQjSbx3mjibPRXOPq978OvmQiEyfnd0hJkHVw7m6WQ2qb2En8mbvk9OthtTRa283O4P0G5Keu1RFrnoWQAjJle6HBs1rCzRts61sTMgh2pUDOO1B74
  template:
    metadata:
      name: tunnel-credentials
      namespace: authentik
