apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkding
spec:
  ingressClassName: traefik
  rules:
    - host: phpmyadmin.lucioschenkel.net
      http:
        paths:
          - backend:
              service:
                name: php-my-admin
                port:
                  number: 80
            path: /
            pathType: Prefix
