apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      name: audiobookshelf
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.17.1
          ports:
            - containerPort: 3005
              protocol: TCP   
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
