apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  selector:
    matchLabels:
      app: audiobookshelf

  template:
    metadata:
      name: audiobookshelf
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000 # this is the node group id
        runAsUser: 1000 # this is the node user id used by linkding container
        runAsGroup: 1000 # this is the node group id

      volumes:
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks

      restartPolicy: Always
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.17.5
          ports:
            - containerPort: 3005
              protocol: TCP   
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          volumeMounts:
            - mountPath: /config
              name: audiobookshelf-config
            - mountPath: /metadata
              name: audiobookshelf-metadata
            - mountPath: /audiobooks
              name: audiobookshelf-audiobooks

