apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:RQfK06lNVvq10aT7dKb+3BokHKEu/5kMf0bIWBJVe16npKRrdkt7VSUUuq6ilZ9JA+6rr6Uu6Hykdz1nHd56IDWnFChaHX8fMEAk3r0SXcbxseVT7peHqQyqaDxy5h/mVMArDeYZL+eONpTyMnyCAiXWHZx67+DUBH5vtvt3vixRLXbGldMXcbvqjZrhtng3X9xx/K4iSye3ZL3M5JG2gdgC2un7EIwdUhgNJ4BECRiDr2KTTS7b5RGaV2vlZkQU0HImJ0IvpaGm2UXEae7PqH8MHfnNJ31x,iv:y3lnf/kKu2aIqwReC6MdI3IqwmEVZZLnBPn3c+rbIKY=,tag:+IQYpYm4ItwiaTED0cEyTg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eq34vq9sccxsrx08a4d27kmw393a7p8ga8wdm4glsnn9nhgsvafqkf75tm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc2k2MFE3ZUZFOGN0U002
            QnAzSy9QamtlM3lyVHR2MktWY1NaaERhaG13CkpDQ1NiV3VpTHNUUW10azJwa1Jv
            Qk9rWjVFaHZSNXJoUUJBNHlvZEFvZGcKLS0tIEpmcitJZ25FZUhZeDlnWlZQRVgr
            M2hFWTRmbTV0MXBKalVzU2UxdjFlMzgKRxJkkm1oBkH5UPbaUOlw/QbU4E3RJJrO
            lNEVmjAaNGMFzxx3zGYeJm0y/sHGIo0ye3SjIgkrqrQZCorVj6v+9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T08:54:49Z"
    mac: ENC[AES256_GCM,data:w9b7bIiUQEI4JESgzpiUlxo8RiMLSh4x4XRWOQdYVozB1XuM17q8XHoUnIhuaqH9cXu+hdINmpSMeXlXZ0UHnaWF5WU0LxmY3pJ1iCmftD5bId37e7r3ForAK3KbVOv6WQAqO5b9db6UYYif3PRCdwMdu+JxRedhU2od2JX7qCk=,iv:35DqnM1O3coE5qF6FeS6oT4OytxRqyHg26TcpUGveqs=,tag:w+bh4oq/NR+24PoDfk8GOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
