apiVersion: v1
data:
    password: ENC[AES256_GCM,data:MAfj72AIQpU=,iv:NgOKh3qXp0A7tSdiFwjpbjtx53Uy02b0h5YsuLsf7V0=,tag:KQ3qZ3TiLQQzk3H34qX8mQ==,type:str]
    user: ENC[AES256_GCM,data:oYYjkppZunY=,iv:czwqG9RsKlznlEj30RVSZZ8oOoB6ejhgD/XqgTbY8nU=,tag:fxR1Qp6mHbhRh+9IIfT2zA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eq34vq9sccxsrx08a4d27kmw393a7p8ga8wdm4glsnn9nhgsvafqkf75tm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvejNxRjZ6aVVNOGxPSzBv
            cHpMS0l2NnEwMEVMbmlUQWMrSTVYOUFXSXo0CldCdnRjOGhVSHdmOUhGU0FHc0pu
            UFd4dEdTK3dsUXlMZTJZcmhKQ1dESDQKLS0tIHBiaDhlNHJRc2ZpZW1JYXR2YnFr
            K2dpYXJQNHpYT3dDVXcvaUl4SWIwQ00KULxPJaJJF8o0jlYh33Ed2IAA8+gFm3ep
            Y8cVRV18WoTPlWhOF92gUsQvQGU4+beuTL40Qn0da6wJyUAZlhlpcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T21:52:12Z"
    mac: ENC[AES256_GCM,data:/snTfTgj21M+lFWYGWTG/hg6STUNYSpFsNtYu1MxUo/zZQszywVX5mpfMZXbH5qrXskp8eNNVYIgAyoUKiEUnPQksPHsX7f9loiBmtgd3fuUvqX7w1+OCigkPbgWZJQ58QAI9f5JLMd7+6XOAlc7N+Xm7Q2nWRreJFBs6AslOUs=,iv:T3L33+Y2KxjUQbE0zLB+rEI6h0b0o4QOhfgD32EhFOg=,tag:xIPkBzj/o14IjYNd+WVWBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
