---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: linkding
spec:
  encryptedData:
    credentials.json: AgBNftdNQYFvngaK9Y4BAFKa2ISH+mFhAXhTdqo2DM9Wv0b86U2uxrulvSg7yoj0m65O71qVQbDmvgvkGpFg1ewq+LkwpZHJSqMd/wjXcRVio7fCUQLKBYgTAOrF+KrJdzwZiCylQ6lKQJOU4jmysp4f8pRPrOfZpWS4qR7T9EqdBJ0g2QbFmwkalyHX/3Jw/rbR26egYCMdI76duU0KCaPsjeBQnQK+iA8y+7Yu82f67qiXXdrGYfQMvsbN+4C3gnGF3vW2I5pZbC8wz86Wq/4cGIACu/qhaAqnne5oblZlhsqf+BJgnT3FxC02ungqGyoRIvO1245lhUuhRYopgEM4zjFoRTr7yN6QsxQ5u5gcuO0UAFKfb0DCt6SjSPsyfO0oSTPpCGznxv8WhUX5wOhtvonSDGlAZOqZzian9Fpc23YK73LT7I8wM3u/RUFeEwe/4mCnl6VoGKOfegXxoHwdtt6rod0pMpU+Xwr0f3Teair+2zdjIxHKDsMs6KIjiGtSZ89sC6q34huBjL81tAvCzVY2JqCCeaizmqogUmYgTWbzh5ctc9QhYBu8k+n7+YjSgNKml1X7oDNeu2KbxdUjS3w5Nh1lcxKD2OZxIQf9NAv9dH+S1Ym1Lwi+NwL2QyL+0xWkBOf7HPnZN8laNWSC5eECMlG8iGMzxFJy6VqKR4OhwO4GrRz5UzFH6TWldZGOEBDArQ6Mv7YmLeTVPeLqXtMj1k4gupmyITr/US/KIhdxzEeWlM4Fyf0TmiR3obb1mGYNwcMWtVMX7KsgB5AFKg0P1uTuNch1YJQB6gRx5ilW6EJfHz9Ow7XP5JoEridu8QEnFOzySQ8W0koh6vd4sw2YVAVij731Bxv9NfDLDUUop/cnz5CLah3+NbUEu2y4vVb6TMgeSGzevntCmP4H9lZLelwKtFC7ZAQ79vz7
  template:
    metadata:
      name: tunnel-credentials
      namespace: linkding
