---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkding-container-env
  namespace: linkding
spec:
  encryptedData:
    LD_SUPERUSER_PASSWORD: AgADTYYITBE2OPGgR0JAUD8PZ1dCQj44x2JwGIOpOO+Fcs6mutpcSVsxXhTxUQW7/Z3oD3ZjWBXTq2nSgsoF4MmIkDMex6b4gj91do7Fg+njp3BUb7K7mCShCzpSob9BF88J2WU72+e/ab9EPd4X3pnTx4TR3JKyiJH+Qc9TadvxyZAdJRNyhRt4ypa41gXPVl4IZcEuSMHdW73YHbRI3fvtNdqiVeufkHM6PlQXlk7bjsYpPGHdOYNBCz41i9LfXIW0ao2/3pFNi1DAk807d+NBZUiXtw0CL58FSkShGKUDuhlALU2D12YaYBAF1Wr69GF37aTOEycAaSfkwBQAOAYFMpOJV9/O/ZbD+odBPJAwjMqIfSSbsWA2g94bK3Qk6RnFfreGjPBGpLLBgV45kanzcdSvhyUM7ZWUa93cuWK7Ho6FwDrxARPtnKe416ck3Dp38nYGv7ozNRZP5SiVdgMTeeyXjvcnhGdf7VhjjQS9guNOl3VzLh5LwiKmXid2wuVvFceC0jOBPFO0lYRHyFgnXi5feINUQNgLrfvJH9fIxBG0Rilpt8iPKkl0M+oTKrfKAUUYdFfgbpmToLYUkg8xKgHRMQ+AAgLrwf/zIu6GIYcx9hGXXSNhC/yzPAReYu7BZCMJvH1rI2XdNzZgZ8Ei0cEF0v5PqUmPNslbffDvVjYCn4jYV8ttNHxUVYLxyMUiad820C4+CMU=
    LD_SUPERUSER_NAME: AgAUwfucKkEszeBP7mho/T7NXk+EInk2p0/VAydtJsAzIQ4OKQV8bUD/5ccAiXoWxDe6aQ12BnZqeuUX3TyY+kOffLrrD5cPZz3QweMaRpmtip6riUh0LFX74Pibjd65o0Yt6sJuZSG6pkkM4WKlrBj0bvG8qqjSRWR9XlcouCz+EYXJr/UdPhatfo1yMzPau0vOMsU8O0xBz/zDB6UVfpPfBYkzVJMGvOFf7cm6kSJ6InTUY46hJ7/KPsCcEYe807d+gbg5edF8o0hHnUlILKJwE0n5Fkjgi5iRbAh7I71jcrumrA2bR9AabH07o3h3oIxqcokux1hOn0BH5ezbjE86OOsoJMo0468pzbZ38ePFgBX2oqqjyb32DpVqUUYpBDN+YshMlu1WnqXaP9sx27IGFhgjyQADa1Bd3LE1w4OnWzRBwdcERtMxony3pV1sZGNISrLJ55S6yasDnw0K1QZC1AD3u+lFwOiPapqjMEyfc3HKTajjUJosppE6fFeCCM0bceYlVxScP8+SYkvdATK6PbECn15QF6GFxaj+VIL9Vh2Z5IxHodkeZ2uZ2J55vToFwWrGhBri+h8arAD2pYi9+RDj/7mbNa1YiqMkj16N0bqqASGqFsrXYRaCNbSE++2EyRVtGf5MSVffce6U0qvlMQuuDrv+UM+hLM1NqLXzNDQP+1x3gG/MHe44pYNvnpU5IIvDB2VSx0AsKXLn
  template:
    metadata:
      name: linkding-container-env
      namespace: linkding
