apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: nextcloud-cluster
spec:
  secretName: innodb-cluster-root-creds
  tlsUseSelfSigned: true
  instances: 3 # Two, secondary read-replicas and one primary instance
  router:
    instances: 1 # One router service
