apiVersion: v1
data:
  PMA_HOST: nextcloud-cluster
kind: ConfigMap
metadata:
  name: php-my-admin-cm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-my-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-my-admin
  template:
    metadata:
      name: php-my-admin
      labels:
        app: php-my-admin
    spec:
      containers:
        - image: phpmyadmin:5.2.1-apache
          name: php-my-admin
          envFrom:
            configMapRef:
              name: php-my-admin-cm
---
apiVersion: v1
kind: Service
metadata:
  name: php-my-admin
spec:
  selector:
    app: php-my-admin
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
