apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-schedule
spec:
  schedule: "0 0 0 * * *" # At midnight every day
  backupOwnerReference: self
  immediate: true
  cluster:
    name: linkding-cluster
