apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:YCkh0iK8vnTVneGpgkqvJEbNnxFDcP8aW95N0A==,iv:OhnoiGHf2cM9ss18zjQ8o60YU081pZ+nmduMJFBwgDo=,tag:Kkg6bupZ1Gek4ij37Y/Rig==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pCy2+3WxO5+2irXsVyhuyaFkuPIiYwpGUsKmg0uLgDD3CAlxhVbt5Vf/ZRQkO0TkD6wiNCakM9Q=,iv:AZshjgXDTMSFdOvFfIHQArySaNIZ+4NElbt0QKpnZz0=,tag:QIkdC8+2r2desc+sE0ZzGQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linode-backup-creds
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eq34vq9sccxsrx08a4d27kmw393a7p8ga8wdm4glsnn9nhgsvafqkf75tm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMTFTMHFxVXBZdXNIdU5s
            L0Q4d0k4OVdQSE0zaWh6dUhKdERXRGNDT0VZClhGUkNheENLYmNrOE81ZnBydUU2
            TmJuaTdoTnNyajFKRWxXdGFNZEtOTFUKLS0tIGIyTEVtRVRXd3p1aGMrZGU4UVdG
            YzVrcE5kNTdwcjg2RlA2NTZVblVxQTAKDXRJP+Q06Mp982WXE0wdpERkTPwl45q1
            UZ73j1zvnlbg7gmqoQjBlvGuInx0QaMcGs1UHAr5rHvDvTmE25z27A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T09:26:12Z"
    mac: ENC[AES256_GCM,data:WZTT9XcOxVmSeMkVFWKyKaS/DE33jsnMYJ47QCxusTyarj+E6l5EyKk24Fr3nLlqBJJh3fe6S254xofsQ6s24VzZJid9QGDHnHBHdYF56ja+hVI1Nwwjjb0SEPrT26VvoTFSiprirdaq9CEGDEWZpTqILDmUBWBcnp/JfHOytUk=,iv:6e3iXhMwRQBBnErpQK6w5TIrl7JrGh4xyY0/54hTpr8=,tag:XgGaLKi9OCLzrGaFfxgR8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
